export const ActionTypes ={
    LOGIN_ACTION:"LOGIN_ACTION",
    SIGNUP_ACTION:"SIGNUP_ACTION",
    GET_PRODUCTS:"GET_PRODUCTS",
    GET_PRODUCT_BY_ID:"GET_PRODUCT_BY_ID",
    LOAD_HOME_SCREEN :"LOAD_HOME_SCREEN",
    UPLOAD_FILE:"UPLOAD_FILE",
    GET_FILE:"GET_FILE",
    GET_ALL_FILE_DATA:"GET_ALL_FILE_DATA"
}